- name: Write noswap systemd service config file
  template:
    src: noswap.service.j2
    dest: /etc/systemd/system/noswap.service
    owner: root
    group: root
    mode: 0644

- name: Enable noswap service
  systemd:
    name: noswap
    state: started
    enabled: true
    daemon_reload: true

- name: Disable selinux
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    replace: 'SELINUX=permissive'

- name: Disable selinux
  shell: setenforce 0
