---
- name: Set CRI runtime endpoint
  shell: |
    sudo crictl config --set runtime-endpoint=unix:///var/run/containerd/containerd.sock \
                       --set image-endpoint=unix:///var/run/containerd/containerd.sock

- name: Enable CRI plugin
  replace:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins.*'
    replace: '#disabled_plugins = ["cri"]'

-  name: Restart containerd service
   systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
